spring.application.name=reactive-crud
spring.r2dbc.url=r2dbc:h2:mem:///reactivecruddb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.r2dbc.username=sa
spring.r2dbc.password=

app.self-base-url=http://localhost:8080
app.performance.max-connections=100
app.performance.pending-acquire-max-count=500
app.performance.max-idle-seconds=30

server.http2.enabled=true
server.compression.enabled=true
server.compression.min-response-size=1024
server.compression.mime-types=application/json,text/plain,text/event-stream
